### ISSUE TITLE
Question: Environment Variables

### ISSUE THREAD

**Issue by jonathanabila** [MattsTechInfo/Meshnet#19]
Hey! Great project!

I set a container using the image and everything worked as expected, however I couldn't find where these NORDVPN_* variables get passed to the container, and where they are used. I wanted to add some extra variables to have more control over the container the settings running with.

Thanks!

**Comment by MattsBos** [comment]
Heya,

All those environment variables are parsed in the various bash scripts which are run to configure and start Meshnet in the container. Out of curiosity, what extra things would you like to configure? If it makes sense to add them it might be a quick adjustment and win. Please let me know!

All current environment variables are used in the three files in the following folder:
[/fs/usr/bin](https://github.com/MattsTechInfo/Meshnet/tree/master/fs/usr/bin)

One exception is the DEBUG option, which is used in the following file:
[fs/etc/services.d/nordvpn/run](https://github.com/MattsTechInfo/Meshnet/blob/master/fs/etc/services.d/nordvpn/run)

**Comment by jonathanabila** [comment]
Kind of related to https://github.com/MattsTechInfo/Meshnet/issues/20. Initially the nickname, that generates a new one every time the container starts.
